LOAD DATA LOCAL INFILE 'category.csv' INTO TABLE Category
    CHARSET 'utf8'
    FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"'
    LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE 'location.csv' INTO TABLE Location
    CHARSET 'utf8'
    FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"'
    LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE 'user.csv' INTO TABLE User
    CHARSET 'utf8'
    FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"'
    LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE 'item.csv' INTO TABLE Item
    CHARSET 'utf8'
    FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"'
    LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE 'Item_Categories.csv' INTO TABLE Item_Categories
    CHARSET 'utf8'
    FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"'
    LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE 'auction.csv' INTO TABLE Auction
    CHARSET 'utf8'
    FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"'
    LINES TERMINATED BY '\n';

LOAD DATA LOCAL INFILE 'bid.csv' INTO TABLE Bid
    CHARSET 'utf8'
    FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"' ESCAPED BY '"'
    LINES TERMINATED BY '\n';